name: ClangFormat check

on:
  workflow_dispatch:

permissions:
  checks: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: check
        working-directory: kernel
        run: make check-format
